In [290]:
# import the data

import pandas as pd
import numpy as np

data = pd.read_csv('online_shoppers_intention-1.csv', header = 0)

SyntaxError: invalid syntax (<ipython-input-290-ef7e6c0a0ec4>, line 4)

In [ ]:
total_rows=len(data.axes[0])
total_cols=len(data.axes[1])
print("Number of Rows: "+str(total_rows))
print("Number of Columns: "+str(total_cols))

In [ ]:
# Checks to see which columns have missing values

data.isnull().any()

In [291]:
# taking a look at the data

data

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,0.016304,1,1,1,1,0.139323,0,0
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,0.016304,2,2,1,2,0.139323,0,0
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,0.016304,4,1,9,3,0.139323,0,0
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,0.016304,3,2,2,4,0.139323,0,0
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,0.016304,3,3,1,4,0.139323,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,0.125072,4,6,1,1,0.139323,1,0
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,0.253502,3,2,1,8,0.139323,1,0
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,0.253502,3,2,1,13,0.139323,1,0
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,0.253502,2,2,3,11,0.139323,0,0
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,0.253502,3,2,1,2,0.249115,1,0

In [292]:
# to numericalize 0 as False and 1 as True for the 'Weekend' and 'Revenue' attributes

data['Weekend'] = data['Weekend'].astype(int)
data['Revenue'] = data['Revenue'].astype(int)

In [293]:
# to check and see if the changes have been made

data

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,0.016304,1,1,1,1,0.139323,0,0
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,0.016304,2,2,1,2,0.139323,0,0
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,0.016304,4,1,9,3,0.139323,0,0
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,0.016304,3,2,2,4,0.139323,0,0
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,0.016304,3,3,1,4,0.139323,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,0.125072,4,6,1,1,0.139323,1,0
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,0.253502,3,2,1,8,0.139323,1,0
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,0.253502,3,2,1,13,0.139323,1,0
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,0.253502,2,2,3,11,0.139323,0,0
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,0.253502,3,2,1,2,0.249115,1,0

In [294]:
# to count every item in a category

data.groupby(['Month'])['Revenue'].count()

Month
0.016304     184
0.100682    1907
0.100694     288
0.108502    3364
0.125072    1727
0.152778     432
0.175520     433
0.191964     448
0.209472     549
0.253502    2998
Name: Revenue, dtype: int64

In [295]:
# to count every item in a category

data.groupby(['VisitorType'])['Revenue'].count()

VisitorType
0.139323    10551
0.188235       85
0.249115     1694
Name: Revenue, dtype: int64

In [296]:
# maps the mean with each item in the category with their positive target value (Revenue)

data.groupby(['Month'])['Revenue'].mean()

Month
0.016304    0.016304
0.100682    0.100682
0.100694    0.100694
0.108502    0.108502
0.125072    0.125072
0.152778    0.152778
0.175520    0.175520
0.191964    0.191964
0.209472    0.209472
0.253502    0.253502
Name: Revenue, dtype: float64

In [297]:
# maps the mean with each item in the category with their positive target value (Revenue)

data.groupby(['VisitorType'])['Revenue'].mean()

VisitorType
0.139323    0.139323
0.188235    0.188235
0.249115    0.249115
Name: Revenue, dtype: float64

In [298]:
# assigns the mean value for each category in their respective column

mdata = data.groupby(['Month'])['Revenue'].mean().to_dict() 
  
data['Month'] =  data['Month'].map(mdata) 

mdata = data.groupby(['VisitorType'])['Revenue'].mean().to_dict() 
  
data['VisitorType'] =  data['VisitorType'].map(mdata) 
  
data

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,0.016304,1,1,1,1,0.139323,0,0
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,0.016304,2,2,1,2,0.139323,0,0
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,0.016304,4,1,9,3,0.139323,0,0
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,0.016304,3,2,2,4,0.139323,0,0
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,0.016304,3,3,1,4,0.139323,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,0.125072,4,6,1,1,0.139323,1,0
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,0.253502,3,2,1,8,0.139323,1,0
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,0.253502,3,2,1,13,0.139323,1,0
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,0.253502,2,2,3,11,0.139323,0,0
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,0.253502,3,2,1,2,0.249115,1,0

In [299]:
# take the 'Revenue' column seoartely as its the the class label
target = data.iloc[:, -1]

# remove the 'Revenue' column from the data
temp = data.iloc[:, 1:17]

In [300]:
# creates a NumPy ndarray object for the data

X = np.array(temp)
y = np.array(target)

In [301]:
# Import the necessary sklearn packages

from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering

In [302]:
kmeans = KMeans(n_clusters=4)

# array contains the cluster assigned to each item/row
clusters = kmeans.fit_predict(X)

In [303]:
%%time

# this cell computes the Rand Index for K-Means

S = 0
D = 0
m = total_rows
RI = 0

# to check each possible pair in the dataset
for i in range(m):
    x1 =  clusters[i]
    y1 = y[i]
    
    for j in range(i+1, m):
        x2 = clusters[j]
        y2 = y[j]
        
        # checks and see if a pair has the same value in 'Revenue' (0 or 1) and is put in the same cluster
        if(x1 == x2 and y1 == y2):
            S = S + 1
            
        # checks and see if a pair has a different value in 'Revenue' (0 or 1) and is put in a different cluster
        if(x1 != x2 and y1 != y2):
            D = D + 1
            
RI = 2*(S + D)/(m*(m-1))
print(RI)

KeyboardInterrupt:

In [304]:
calg = AgglomerativeClustering(n_clusters=4)

# array contains the cluster assigned to each item/row
clusters2 = calg.fit_predict(X)

KeyboardInterrupt:

In [ ]:
%%time

# this cell computes the Rand Index for Complete-Linkage AGNES

S = 0
D = 0
m = total_rows
RI = 0

# to check each possible pair in the dataset
for i in range(m):
    x1 =  clusters2[i]
    y1 = y[i]
    
    for j in range(i+1, m):
        x2 = clusters2[j]
        y2 = y[j]
        
        # checks and see if a pair has the same value in 'Revenue' (0 or 1) and is put in the same cluster
        if(x1 == x2 and y1 == y2):
            S = S + 1
        
        # checks and see if a pair has a different value in 'Revenue' (0 or 1) and is put in a different cluster
        if(x1 != x2 and y1 != y2):
            D = D + 1
            
RI = 2*(S + D)/(m*(m-1))
print(RI)